// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Data;

#nullable disable

namespace QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Migrations
{
    [DbContext(typeof(KhoaHocDbContext))]
    [Migration("20261009011520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.BuoiHoc", b =>
                {
                    b.Property<int>("MaBuoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBuoiHoc"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GiangVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaBuoiHoc");

                    b.HasIndex("MaLop");

                    b.ToTable("BuoiHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.ChuongTrinhDaoTao", b =>
                {
                    b.Property<int>("MaChuongTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuongTrinh"));

                    b.Property<string>("EmailLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaChuongTrinh");

                    b.HasIndex("TenChuongTrinh")
                        .IsUnique();

                    b.ToTable("ChuongTrinhDaoTaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.DangKyHoc", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDongHocPhi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetGiaoVu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("SoTienDaDong")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLop");

                    b.ToTable("DangKyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrinhDoHocVan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.KetQuaHocTap", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<decimal>("DiemChuyenCan")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DiemCuoiKhoa")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DiemTongKet")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaDangKy")
                        .IsUnique();

                    b.ToTable("KetQuaHocTaps");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("GiangVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HanDangKy")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaChuongTrinh")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NgayBatDauDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrinhDoDauVao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YeuCauHocVien")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaChuongTrinh");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.BuoiHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.LopHoc", "LopHoc")
                        .WithMany("BuoiHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.DangKyHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.HocVien", "HocVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.LopHoc", "LopHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.HocVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("HocVien")
                        .HasForeignKey("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.HocVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.KetQuaHocTap", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.DangKyHoc", "DangKyHoc")
                        .WithOne("KetQuaHocTap")
                        .HasForeignKey("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.KetQuaHocTap", "MaDangKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DangKyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.LopHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.ChuongTrinhDaoTao", "ChuongTrinh")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaChuongTrinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongTrinh");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.DangKyHoc", b =>
                {
                    b.Navigation("KetQuaHocTap");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.HocVien", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.LopHoc", b =>
                {
                    b.Navigation("BuoiHocs");

                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A1HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
